apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-miit
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0018-tenant/tkrw-pr712-0075-0018-app/devfile-sample-miit@sha256:5078d6967ee48c6dce8383fc496ce06db97f6dcc3c9a02df00f338b96ca3f6a2
        name: my-nodejs
        resources: {}
status: {}
